### PR TITLE
Added functions to search the list of followers and following by a user

### PR DESCRIPTION
**Pull request by ev4ndropc**
Added the function to search for a user in the list of followers and following.

Alt text

### CODE REVIEW

**Comment by Gimenz** [comment]
wow amazing feature, but sorry i'm too slow to respon this, may on the next week i'll review this. thanks for making the PR

**Comment by Gimenz** [comment]
hi @ev4ndropc , can you add the types file at src/types ?

**Comment by ev4ndropc** [comment]
> hi @ev4ndropc , can you add the types file at src/types ?

done

**Comment by Gimenz** [comment]
how about request response?

**Comment by ev4ndropc** [comment]
> how about request response?

Sorry but I don't have much knowledge with typescript

**Comment by Gimenz** [comment]
oh okay, i'm sorry. but i appreciate for your PR, thanks

**Pull request merged**
