### PR TITLE
serverless functions compatibility

### PR DESCRIPTION
**Pull request by pouryapb**
#6 
Here you go. this should work. I wrote some lazy test codes that does not mean the code is 100% working 😄 . I'm sure you can write better tests later.

### CODE REVIEW

**Comment by Gimenz** [comment]
ah thanks for your PR, i'll review the code later. i'm too lazy for now haha.

**Comment by pouryapb** [comment]
Good one

**Comment by pouryapb** [comment]
now that I look again, I just needed to cover the constructor and `this.setCookie()` function. `this.cookie.get()` is just reading file and it shouldn't be a problem. why are you even storing it in a text file? I mean it's more convenient if it's in an environment variable.

**Comment by Gimenz** [comment]
ey bro, sorry if you waited too long. but can you delete test using mocha, i never use it haha.

**Comment by Gimenz** [comment]
> now that I look again, I just needed to cover the constructor and `this.setCookie()` function. `this.cookie.get()` is just reading file and it shouldn't be a problem. why are you even storing it in a text file? I mean it's more convenient if it's in an environment variable.

I didn't think about it

**Comment by Gimenz** [comment]
sorry, i've fix it :D but thanks for making this library more better

**Pull request closed without merging**
